name: heaven_kit
description: A new Flutter package.
version: 1.0.0+1
environment:
  sdk: ">=2.2.3 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^3.2.0
  redux: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.4.0
flutter:
  uses-material-design: true

